### Title + Text + Their Individual Counts
---

### Import Relevant Libraries

In [3]:
# For dataset manipulation
import numpy as np
import pandas as pd
# For punctuation count
import spacy
# For readability ease count
import textstat
# For progress bar
from tqdm.notebook import tqdm
tqdm.pandas()

import re
import string
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

### Download Resources

In [4]:
# Required once
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\njkes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\njkes\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\njkes\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\njkes\AppData\Roaming\nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\njkes\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

### Custom Functions

In [ ]:
# Helper to convert POS tags for lemmatizer
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# Full cleaning function
def content_cleaner(text):
    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove content inside square brackets
    text = re.sub(r'\[.*?\]', '', text)

    # Remove newline characters
    text = text.replace('\n', ' ')

    # Remove words with digits (e.g. "covid19")
    text = re.sub(r'\w*\d\w*', '', text)

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords and punctuation
    tokens = [
        word for word in tokens
        if word not in stopwords.words('english')
        and word not in string.punctuation
        and word.isalpha()
    ]

    # POS tagging for lemmatization
    pos_tags = pos_tag(tokens)

    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [
        lemmatizer.lemmatize(word, get_wordnet_pos(pos)) for word, pos in pos_tags
    ]

    # Rejoin
    cleaned_text = ' '.join(lemmatized_tokens)

    return cleaned_text

### Fully Clean Combined Data

In [6]:
df_all = pd.read_csv("../../Datasets/Dataset1_master_combined_counts_cleaned_1.csv")

In [8]:
df_all = df_all.drop(columns=["Unnamed: 0"]).reset_index(drop=True)

In [11]:
df_all

,combined_data,combined_word_count,combined_punct_count,combined_readability_ease,label
0,Many 'lost' voters say they have found their c...,1101,184,50.06,1
1,"Iranian Revolutionary Guards commander, anothe...",409,50,28.77,1
2,Cambodian leader gets China's backing as West ...,602,58,48.13,1
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,442,52,61.97,0
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,29,4,25.12,0
...,...,...,...,...,...
39100,Hillary’s Message To Former Miss Universe Cal...,260,39,63.39,0
39101,SENIOR CIA INTEL: “Wiretapping of Trump Transi...,12,5,17.00,0
39102,Ex-Georgian leader Saakashvili barges across U...,507,61,49.35,1
39103,Trump Stole An Idea From North Korean Propaga...,887,160,69.72,0
39104,WATCH JUDGE TELL DISRESPECTFUL GANGBANGER Taxp...,817,86,72.46,0

In [12]:
df_all['combined_data'] = df_all['combined_data'].progress_apply(content_cleaner)

  0%|          | 0/39105 [00:00<?, ?it/s]

In [13]:
df_all

,combined_data,combined_word_count,combined_punct_count,combined_readability_ease,label
0,many voter say find candidate trump york reute...,1101,184,50.06,1
1,iranian revolutionary guard commander another ...,409,50,28.77,1
2,cambodian leader get china back west condemns ...,602,58,48.13,1
3,grand wizard maine gov right call black men de...,442,52,61.97,0
4,granny hillary clinton blow activist confront ...,29,4,25.12,0
...,...,...,...,...,...
39100,hillary message former miss universe call miss...,260,39,63.39,0
39101,senior cia intel wiretapping trump transition ...,12,5,17.00,0
39102,leader saakashvili barge across ukraine border...,507,61,49.35,1
39103,trump stole idea north korean propaganda parod...,887,160,69.72,0
39104,watch judge tell disrespectful gangbanger taxp...,817,86,72.46,0

### Save the updated dataset

In [14]:
df_all.to_csv("../../Datasets/Dataset1_master_combined_counts_cleaned_2.csv")